"""add_social_oauth_columns

Revision ID: 28da83e0b15f
Revises: 62f9c97d9b0a
Create Date: 2026-02-12 14:51:37.976707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28da83e0b15f'
down_revision: Union[str, None] = '62f9c97d9b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
