"""Add soft deletes to clients and projects

Revision ID: 3a52e7a079c1
Revises: dfcf818c9397
Create Date: 2026-03-21 01:20:23.523752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a52e7a079c1'
down_revision: Union[str, None] = 'dfcf818c9397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_clients_deleted_at'), 'clients', ['deleted_at'], unique=False)
    op.add_column('projects', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_projects_deleted_at'), 'projects', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_deleted_at'), table_name='projects')
    op.drop_column('projects', 'deleted_at')
    op.drop_index(op.f('ix_clients_deleted_at'), table_name='clients')
    op.drop_column('clients', 'deleted_at')
    # ### end Alembic commands ###
