"""remove_linkedin_id

Revision ID: 3a6ed180b03d
Revises: 3a52e7a079c1
Create Date: 2026-03-22 16:49:56.637432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a6ed180b03d'
down_revision: Union[str, None] = '3a52e7a079c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_linkedin_id', table_name='users')
    op.drop_column('users', 'linkedin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('linkedin_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('ix_users_linkedin_id', 'users', ['linkedin_id'], unique=True)
    # ### end Alembic commands ###
