"""add_social_oauth_columns

Revision ID: 62f9c97d9b0a
Revises: 003_add_saas_tables
Create Date: 2026-02-12 14:44:51.786778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f9c97d9b0a'
down_revision: Union[str, None] = '003_add_saas_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clients_phone_key', 'clients', type_='unique')
    op.drop_constraint('github_cache_project_id_key', 'github_cache', type_='unique')
    op.drop_index('ix_github_cache_project_id', table_name='github_cache')
    op.create_index(op.f('ix_github_cache_project_id'), 'github_cache', ['project_id'], unique=True)
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('github_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('linkedin_id', sa.String(length=255), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_linkedin_id'), 'users', ['linkedin_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_linkedin_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'linkedin_id')
    op.drop_column('users', 'github_id')
    op.drop_column('users', 'google_id')
    op.drop_index(op.f('ix_github_cache_project_id'), table_name='github_cache')
    op.create_index('ix_github_cache_project_id', 'github_cache', ['project_id'], unique=False)
    op.create_unique_constraint('github_cache_project_id_key', 'github_cache', ['project_id'])
    op.create_unique_constraint('clients_phone_key', 'clients', ['phone'])
    # ### end Alembic commands ###
