name: Publish Docker Images

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}

      - name: Lowercase Repo Name
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push Backend
        uses: docker/build-push-action@v7
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ env.REPO }}-backend:latest,ghcr.io/${{ env.REPO }}-backend:${{ github.event.release.tag_name }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ env.REPO }}-frontend:latest,ghcr.io/${{ env.REPO }}-frontend:${{ github.event.release.tag_name }}
